spring:
  application:
    name: import-xml
  datasource:
    url: jdbc:mysql://82.202.130.166:3306/myapp_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: myapp_user
    password: myapp_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000   # 2 минут (в миллисекундах)
      idle-timeout: 60000    # 1 минута (в миллисекундах)
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          characterEncoding: UTF-8
          useUnicode: true
  messages:
    encoding: UTF-8
    locale: ru_RU
    basename: messages
    fallback-to-system-locale: false
    cache-duration: 3600
    use-code-as-default-message: false
    always-use-message-format: false
    default-encoding: UTF-8

server:
  port: 8081
  servlet:
    context-path: /api

import-xml:
  api:
    base-url: ${IMPORT-XML_API_URL:https://api2.gifts.ru}
    username: 19405_xmlexport
    password: 15101977
    site-url: https://placlobusaf.beget.app
    ip: 82.202.130.166
  import-section:
    directory: /opt/import-xml/import
    rate-limit:
      delay: 1000
    files:
      product: product.xml
      stock: stock.xml
      tree: tree.xml
      filters: filters.xml
      complects: complects.xml
      catalogue: catalogue.xml
  xml-download:
    temp-dir: ./temp/xml
    rate-limit: 5
    retry-attempts: 3
    retry-delay: 5
  sync:
    cron: "0 0 */4 * * *"

opencart:
  base-url: https://placlobusaf.beget.app
  api-key: 3uCysrJ7SEwgfL8QLQkfULYkuv1ZTCzNDH2yLOXcUN36H08UQffB4vdJ00jkcGSIbPZBJFkjY4VuwULP734JqswAVgiMSXXRfAENvVBUqImNiHSYua0YUkAL8pmqApidqkrnljKFtNRm3whbJ4imm4D6nnnsmMUnaKFyJIQrVlgcSyxlNL4IDTBh44uss7DrXpK46kRZHyqqZdKY1CU7S7hJyXU8lQBqJcsbnPxGswl66OtMCQjq4LWEfQmVUoQK
  username: admin
  password: "&&S!B87d"
  sync:
    batch-size: 100
    retry-attempts: 3
    retry-delay: 5000
    cron: "0 0 */4 * * *"  # Каждые 4 часа

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.http.client: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    import_xml: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
    file: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

http:
  client:
    max-connections: 5
    connection-timeout: 30000
    socket-timeout: 30000
    retry-attempts: 3
    retry-delay: 5
    rate-limit: 5
    connect-timeout: 5000
    read-timeout: 10000
